[BE] 좋아요 취소 기능 구현
mariage-kr/mariage pull request #233
Opened 2023-05-20 03:18 UTC by rrimm

# 개요

#214 좋아요 취소 기능 구현

## 한 일

- [X] 좋아요 취소 비즈니스 로직 구현
- [ ] 테스트 코드 작성

2023-05-21 09:22 UTC, KIMSEI1124 commented
@rrimm 다 되셨으면 합쳐도 되는걸까요?

2023-05-21 09:27 UTC, KIMSEI1124 requested changes
`HttpStatus` 하나만 수정하면 좋을 것 같아요.

2023-05-21 09:27 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/like/controller/LikeController.java
> +    @DeleteMapping("/user/review/like/cancel")
별건 아니지만 ( 사실 저도 이렇게는 안했는데 ) 조언을 하자면 `post`, `delete` 로 분리가 되기 떄문에 두개의 url은 동일하게 해도 괜찮아요.

`/user/review/like` 로 통일해도 괜찮다는 의미였습니다.

2023-05-21 09:27 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/like/controller/LikeController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
삭제 인데 CREATED 이네요?.. OK가 좋을 것 같아요

2023-05-21 09:53 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/like/controller/LikeController.java
> +    @DeleteMapping("/user/review/like/cancel")
앗ㅎㅎ 꿀팁 감사합니다! 변경하였습니다.

2023-05-21 09:53 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/like/controller/LikeController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
ok로 변경하였습니다!

2023-05-21 09:56 UTC, rrimm commented
@KIMSEI1124 기능 구현은 우선 했는데 효율적으로 실행되는 코드인지는..ㅎ 리팩토링이 필요한 것 같기도 합니다ㅠㅜ

2023-05-22 00:49 UTC, KIMSEI1124 requested changes

2023-05-22 01:15 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/like/service/LikeService.java
> +        review.getLikes().remove(like);
알려주셔서 감사합니다! 앞으로 로직 구현할 때 참고하겠습니다! 알려주신대로 변경하였습니다.

2023-05-22 01:16 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/like/service/LikeService.java
> +        review.getLikes().remove(like);
```
select l1_0.like_id from liked l1_0 where l1_0.member_id=? and l1_0.review_id=? fetch first ? rows only
select l1_0.like_id from liked l1_0 where l1_0.member_id=2 and l1_0.review_id=1 fetch first 1 rows only;
2023-05-22T10:15:39.724+09:00  INFO 20972 --- [           main] p6spy                                    : #1684718139724 | took 1ms | statement | connection 3| url jdbc:h2:tcp://localhost/~/test
insert into liked (like_id, member_id, review_id) values (default, ?, ?)
insert into liked (like_id, member_id, review_id) values (default, 2, 1);
2023-05-22T10:15:39.741+09:00  INFO 20972 --- [           main] p6spy                                    : #1684718139741 | took 0ms | statement | connection 3| url jdbc:h2:tcp://localhost/~/test
select l1_0.like_id,l1_0.member_id,l1_0.review_id from liked l1_0 where l1_0.member_id=? and l1_0.review_id=?
select l1_0.like_id,l1_0.member_id,l1_0.review_id from liked l1_0 where l1_0.member_id=2 and l1_0.review_id=1;
2023-05-22T10:15:39.755+09:00  INFO 20972 --- [           main] p6spy                                    : #1684718139755 | took 0ms | statement | connection 3| url jdbc:h2:tcp://localhost/~/test
delete from liked where like_id=?
delete from liked where like_id=1;
2023-05-22T10:15:39.760+09:00  INFO 20972 --- [           main] p6spy                                    : #1684718139760 | took 0ms | statement | connection 3| url jdbc:h2:tcp://localhost/~/test
select l1_0.like_id from liked l1_0 where l1_0.member_id=? and l1_0.review_id=? fetch first ? rows only
select l1_0.like_id from liked l1_0 where l1_0.member_id=2 and l1_0.review_id=1 fetch first 1 rows only;
2023-05-22T10:15:39.887+09:00  INFO 20972 --- [           main] p6spy    
```
좋아요 취소 테스트 시에 이렇게 나오는 걸 보니.. 두번 나가는 것 같기도 합니다ㅠ

2023-05-22 01:20 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/like/exception/LikeErrorCode.java
> +    LIKE_NOT_FOUND_IN_REVIEW(404, "Like_04", "리뷰에 해당 좋아요가 없습니다."),
알려주신대로 수정하였습니다!

2023-05-22 01:25 UTC, KIMSEI1124 requested changes

2023-05-22 01:25 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/member/domain/Member.java
> +
피드백한 내용으로 수정해 주세요.

2023-05-22 01:25 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/review/domain/Review.java
> +    }
`Member` 와 동일한 피드백입니다.

2023-05-22 01:30 UTC, KIMSEI1124 requested changes

2023-05-22 01:30 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/like/service/LikeService.java
> +        likeRepository.delete(like);
맨 뒤로 가는게 좋지 않을까 생각이 듭니다!..

2023-05-22 01:35 UTC, KIMSEI1124 approved these changes

2023-05-22 01:36 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/member/domain/Member.java
> +
수정하였습니다!

2023-05-22 01:36 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/review/domain/Review.java
> +    }
수정 완료하였습니다!

2023-05-22 01:36 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/like/service/LikeService.java
> +        likeRepository.delete(like);
피드백해주신대로 수정하였습니다.

2023-05-22 01:37 UTC, merged