[BE] 카테고리 조회 기능 구현
mariage-kr/mariage pull request #79
Opened 2023-05-04 13:56 UTC by rrimm

# 개요

#76 상위카테고리 조회 기능 추가 

## 한 일

- [X] 국내, 해외별 카테고리 조회 기능 구현

## 할 일
- [X] 예외처리 기능

2023-05-05 05:04 UTC, KIMSEI1124 reviewed
피드백 관련 내용을 남겨 드렸습니다.

1. `Response` 에 제가 만들어 본 `Json` 포멧으로 한번 고민해 보세요.
2. `@Transactional` 어노테이션에 대해서 한번 생각해보세요.
3. `@JoinColumn` 어노테이션에 대해서 한번 생각해보세요.

2023-05-05 05:04 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/product/domain/Product.java
> +    private DrinkLowerCategory lowerCategory;
`@JoinColumn` 에 대해서 한번 고민해 보시면 좋을 것 같아요.
아래에 동일한 피드백을 남겼습니다.

2023-05-05 05:04 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/product/controller/ProductController.java
> +    @PostMapping("/product/save")
추후에 생각할 내용이지만 제품 등록은 관리자만 가능하게 할 텐데 이렇게 하면 회원 가입 하지 않은 사용자도 가능하니깐 어떻게 하면 좋을지 생각해보시면 좋을 것 같아요.

2023-05-05 05:04 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/service/DrinkUpperCategoryService.java
> +    @Transactional
DB에 저장하는 로직이 없는 거 같은데 필요할까요?!

2023-05-05 05:04 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/dto/DrinkUpperCategoryResponse.java
제가 컨트롤러에 남긴 피드백을 토대로 한번 생각해 보시면 좋을 것 같아요.

2023-05-05 05:22 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/product/domain/ProductRepository.java
> +    Product save(Product product);
이건...삭제했어야 했는데 같이 커밋을 해버렸네요... 죄송합니다ㅠㅠ 삭제하겠습니다!

2023-05-05 06:50 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/controller/CategoryController.java
> +    @GetMapping("/categories/{origin}")
```json
{
    "category": [
        {
            "region": "local",
            "categories": [
                {
                    "name": "LOCAL_SOJU",
                    "value": "소주"
                },
                {
                    "name": "LOCAL_BEER",
                    "value": "맥주"
                },
                {
                    "name": "LOCAL_TRADITIONAL",
                    "value": "전통주"
                },
                {
                    "name": "LOCAL_ETC",
                    "value": "기타"
                }
            ]
        },
        {
            "region": "foreign",
            "categories": [
                {
                    "name": "FOREIGN_SPIRITS",
                    "value": "증류주"
                },
                {
                    "name": "FOREIGN_BEER",
                    "value": "맥주"
                },
                {
                    "name": "FOREIGN_WINE",
                    "value": "와인"
                },
                {
                    "name": "FOREIGN_WHISKEY",
                    "value": "위스키"
                },
                {
                    "name": "FOREIGN_ETC",
                    "value": "기타"
                }
            ]
        }
    ]
}
```
조금 더 수정해 봤습니다 다음과 같이 하는게 더 좋은 방식이네요.

2023-05-07 05:48 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/review/domain/Review.java
>      private FoodCategory foodCategory;
이전 테이블 구조 기준에서 우선 주석처리하고 변경하다보니 코드 관련으로 미흡했습니다 ㅠㅠ 수정하였습니다!

2023-05-07 05:48 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/product/domain/Product.java
> +    private DrinkLowerCategory lowerCategory;
확인했습니다 감사합니다!

2023-05-07 05:51 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/product/controller/ProductController.java
> +    @PostMapping("/product/save")
로그인 관리쪽에서 admin으로 인증 뒤 관리할 수 있게 하는 정도로 생각은 하고 있는데... 기능 구현 뒤에 좀더 고민해보겠습니다!

2023-05-07 05:51 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/category/service/DrinkUpperCategoryService.java
> +    @Transactional
삭제했습니다!

2023-05-07 06:04 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/category/controller/CategoryController.java
> +    @GetMapping("/categories/{origin}")
아래와 같이 반환되도록 변경하였습니다!
```
[
    {
        "region": "local",
        "categories": [
            {
                "name": "LOCAL_SOJU",
                "value": "소주"
            },
            {
                "name": "LOCAL_BEER",
                "value": "맥주"
            },
            {
                "name": "LOCAL_TRADITIONAL",
                "value": "전통주"
            },
            {
                "name": "LOCAL_ETC",
                "value": "기타"
            }
        ]
    },
    {
        "region": "foreign",
        "categories": [
            {
                "name": "FOREIGN_SPIRITS",
                "value": "증류주"
            },
            {
                "name": "FOREIGN_BEER",
                "value": "맥주"
            },
            {
                "name": "FOREIGN_WINE",
                "value": "와인"
            },
            {
                "name": "FOREIGN_WHISKEY",
                "value": "위스키"
            },
            {
                "name": "FOREIGN_ETC",
                "value": "기타"
            }
        ]
    }
] 
```

2023-05-07 12:32 UTC, KIMSEI1124 requested changes
추가 코멘트 달았습니다.

`"local"` 와 같이 반복적으로 사용하는 것을 해결해보세요.

2023-05-07 12:32 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/controller/CategoryController.java
> +    @GetMapping("/categories")
추후 음식, 하위 카테고리도 있을 테니깐 `/categories/upper` 이런식으로 하는게 좋을 것 같은데 어떻게 생각하시나요?

2023-05-07 12:32 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/domain/DrinkUpperCategory.java
> +    FOREIGN_ETC(9, "기타", "foreign");
`"local"` 이 4번 반복, `"foreign"` 이 5번 반복 되는데 어떻게 해결하면 좋을까요?

2023-05-07 12:32 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/dto/DrinkUpperCategoryResponse.java
> +    @Builder
한 개의 파라미터인 경우인데 굳이 `@Builder` 를 사용하는 이유가 있으신가요?

2023-05-07 12:32 UTC, KIMSEI1124 commented on backend/src/main/java/com/multi/mariage/category/service/DrinkUpperCategoryService.java
> +                .toList();
위에 적어둔 `"local"`, `"foreign"` 을 해결해 보면서 어떻게 하면 좋을지 생각해보면 좋을 것 같습니다!

한 30분 고민하다가 안되시면 말씀해주세요.

2023-05-07 13:39 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/category/service/DrinkUpperCategoryService.java
> +                .toList();
```
@Getter
public enum DrinkUpperCategory {
    LOCAL_SOJU(1, "소주"),
    LOCAL_BEER(2, "맥주"),
    LOCAL_TRADITIONAL(3, "전통주"),
    LOCAL_ETC(4, "기타"),
    FOREIGN_SPIRITS(5, "증류주"),
    FOREIGN_BEER(6, "맥주"),
    FOREIGN_WINE(7, "와인"),
    FOREIGN_WHISKEY(8, "위스키"),
    FOREIGN_ETC(9, "기타");
    private final int id;
    private final String name;

    DrinkUpperCategory(int id, String name) {
        this.id = id;
        this.name = name;
    }
}
```
enum을 이렇게 변경한 다음에, service의 코드를 변경하는 방식은 어떨까요?

기존 코드
```
List<String> regionList = categories.stream()
                .map(DrinkUpperCategory::getRegion)
                .distinct()
                .toList();

        for (String region : regionList) {
            List<DrinkUpperCategoriesResponse> categoryList = categories.stream()
                    .filter(category -> category.getName().contains(region))
                    .map(category -> DrinkUpperCategoriesResponse.builder()
                            .name(category.name())
                            .value(category.getName())
                            .build())
                    .collect(Collectors.toList());
```
변경 코드
```
List<String> regionList = Arrays.asList("local", "foreign");

        for (String region : regionList) {
            List<DrinkUpperCategoriesResponse> categoryList = categories.stream()
                    .filter(category -> category.name().toLowerCase().contains(region))
                    .map(category -> DrinkUpperCategoriesResponse.builder()
                            .name(category.name())
                            .value(category.getName())
                            .build())
                    .collect(Collectors.toList());
```

그런데 좋은 방식인지 확신이 안드네요..ㅜㅠ

2023-05-07 13:49 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/category/dto/DrinkUpperCategoryResponse.java
> +    @Builder
다른 코드를 관리할 때 NoArgsConstructor의 PROTECTED 설정 때문에 객체 생성이 안됐어서 한 개의 파라미터인데도 builder를 사용했습니다ㅠㅠ PROTECTED 설정에 대한 이해가 부족했습니다..
`DrinkUpperCategoryResponse drinkUpperCategoryResponse = new DrinkUpperCategoryResponse(responseList);` 
이렇게 수정하겠습니다!

2023-05-07 13:57 UTC, rrimm commented on backend/src/main/java/com/multi/mariage/category/controller/CategoryController.java
> +    @GetMapping("/categories")
넵 수정이 필요할 것 같습니다! 감사합니당!!

2023-05-08 05:53 UTC, KIMSEI1124 reviewed
로직은 다 짜신거 같은데 이제 테스트 코드 작성하시나요?!

2023-05-08 06:17 UTC, rrimm commented
넵 테스트 코드 작성 중입니다.. @KIMSEI1124

2023-05-08 12:16 UTC, KIMSEI1124 requested changes
한 번 생각해보시고 모르겠으면 질문해주세요!

2023-05-08 12:16 UTC, KIMSEI1124 commented on backend/src/test/java/com/multi/mariage/category/service/DrinkUpperCategoryServiceTest.java
> +    }
사용하지 않는 함수는 삭제해주세요.

2023-05-08 12:16 UTC, KIMSEI1124 commented on backend/src/test/java/com/multi/mariage/category/service/DrinkUpperCategoryServiceTest.java
> +    }
[AssertJ 알아보기 (부제 : Jupiter, Hamcrest 맛보기 )](https://loopstudy.tistory.com/287)

참고하시고 `AssertJ` 로 한번 마이그레이션 해보세요! 현재는 `AssertJ`를 더 많이 사용합니다.

2023-05-08 12:16 UTC, KIMSEI1124 commented on backend/src/test/java/com/multi/mariage/category/controller/CategoryControllerTest.java
> +                .andExpect(status().isOk());
더 추가할 내용이 있는데 다른 컨트롤러를 보시고 생각해보시면 좋을 것 같아요.

2023-05-08 12:37 UTC, rrimm commented on backend/src/test/java/com/multi/mariage/category/service/DrinkUpperCategoryServiceTest.java
> +    }
넵 삭제하였습니다.

2023-05-08 18:00 UTC, rrimm commented on backend/src/test/java/com/multi/mariage/category/controller/CategoryControllerTest.java
> +                .andExpect(status().isOk());
공식 문서나 다른 컨트롤러 코드를 참고해서 responseFields를 추가하였습니다. 맞게 했는지 모르겠네요..
```
mockMvc.perform(get("/api/categories/upper"))
                .andDo(print())
                .andDo(document("Category/FindUpperCategory",
                    preprocessResponse(prettyPrint()),
                    responseFields(
                            fieldWithPath("category").description("주류 상위 카테고리"),
                            fieldWithPath("category[].region").description("주류 원산지"),
                            fieldWithPath("category[].categories").description("주류 상위 카테고리"),
                            fieldWithPath("category[].categories[].name").description("주류 상위 카테고리 지칭"),
                            fieldWithPath("category[].categories[].value").description("주류 상위 카테고리 명칭")
                        )
                )
        )
                .andExpect(status().isOk());
```

2023-05-08 18:17 UTC, rrimm commented on backend/src/test/java/com/multi/mariage/category/service/DrinkUpperCategoryServiceTest.java
> +    }
주신 자료 참고하였습니다. 감사합니다! service 테스트 코드를 변경하여 커밋하였습니다. c76f297

2023-05-09 00:52 UTC, KIMSEI1124 approved these changes
상위 카테고리 조회 기능 합치겠습니다.

2023-05-09 00:53 UTC, merged